package model.enums;

@SuppressWarnings("SpellCheckingInspection")
public enum MapAssetType {
    //Buildings
    HEADQUARTER, LOOKOUT_TOWER, PERIMETER_TOWER, DEFENSE_TOWER, SQUARE_TOWER, CIRCULAR_TOWER, BEAR_FACTORY, BAKERY, WHEAT_FIELD,
    GRAIN_FIELD, DIARY_FACTORY, APPLE_GARDEN, POLTURNER, FLETCHER, BLACKSMITH, ARMOURER, WOOD_CUTTER, QUARRY, SMALL_WALL, WALL,
    PITCH_RIG, IRON_MINE, MILL, INN, HAUNTING_GROUND, SIEGE_TENT, STABLE, BARRACK, MERCENARY_POST, ENGINEER_GUILD,
    CHURCH, CATHEDRAL, TUNNELER_POST, HOUSE, SMALL_GATEHOUSE, BIG_GATEHOUSE, ARMOURY, FOOD_STORAGE, STORE_HOUSE, STORE, OX_TETHER,
    //Units
    ARCHER, CROSSBOWMAN, SPEARMAN, PIKEMAN, MACEMAN, SWORDSMAN, KNIGHT, TUNNELER, BLACK_MONK, ARCHER_BOW, SLAVE, SLINGER, ASSASSIN,
    HORSE_ARCHER, ARABIAN_SWORDSMAN, FIRE_THROWER, ENGINEER, LADDER_MAN,
    DOG, COW,
    //Siege warfare
    BATTERING_RAM, CATAPULT, STABLE_CATAPULT, FIRE_CATAPULT, SIEGE_TOWER, MOBILE_SHIELD,
    //Nature objects
    TREE, CLIFF


}
