package model.enums;

public enum MapAssetType {
    LOOKOUT_TOWER, PERIMETER_TOWER, DEFENSE_TOWER, SQUARE_TOWER, CIRCULAR_TOWER, BEAR_FACTORY, BAKERY, WHEAT_FIELD, GRAIN_FIELD, DIARY_FACTORY, APPLE_GARDEN, POLTURNER, FLETCHER, BLACKSMITH, ARMOURER, WOOD_CUTTER, QUARRY, PITCH_RIG, IRON_MINE, MILL, INN, HAUNTING_GROUND, SIEGE_TENT, STABLE, BARRACK, MERCENARY_POST, ENGINEER_GUILD, CHURCH, CATHEDRAL, TUNNELER_POST, HOUSE, SMALL_GATEHOUSE, BIG_GATEHOUSE, ARMOURY, FOOD_STORAGE, STORE_HOUSE, STORE, OX_TETHER,
}
